import os
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer

def generate_invoice_pdf(invoice_id, customer_name, items, subtotal, gst_total, grand_total):
    output_dir = os.path.join(os.path.dirname(__file__), "generated_invoices")
    os.makedirs(output_dir, exist_ok=True)

    file_path = os.path.join(output_dir, f"invoice_{invoice_id}.pdf")

    doc = SimpleDocTemplate(
        file_path,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
    )

    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("<b>GST Management System</b>", styles["Title"]))
    story.append(Paragraph(f"Invoice #{invoice_id}", styles["Heading2"]))
    story.append(Spacer(1, 8))
    story.append(Paragraph(f"<b>Customer:</b> {customer_name}", styles["BodyText"]))
    story.append(Spacer(1, 12))

    data = [["Product", "Qty", "Unit Price", "GST %", "GST Amount", "Total"]]

    for item in items:
        data.append([
            item["product_name"],
            str(item["quantity"]),
            f"Rs. {item['price']:.2f}",
            f"{item['gst_rate']:.2f}%",
            f"Rs. {item['gst_amount']:.2f}",
            f"Rs. {item['total']:.2f}",
        ])

    table = Table(
        data,
        colWidths=[52*mm, 15*mm, 28*mm, 20*mm, 30*mm, 30*mm]
    )
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563EB")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [
            colors.white,
            colors.HexColor("#F8FAFC")
        ]),
        ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
    ]))

    story.append(table)
    story.append(Spacer(1, 16))

    totals = [
        ["Subtotal", f"Rs. {subtotal:.2f}"],
        ["GST", f"Rs. {gst_total:.2f}"],
        ["Grand Total", f"Rs. {grand_total:.2f}"],
    ]

    totals_table = Table(totals, colWidths=[45*mm, 35*mm], hAlign="RIGHT")
    totals_table.setStyle(TableStyle([
        ("FONTNAME", (0, 2), (-1, 2), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ALIGN", (1, 0), (-1, -1), "RIGHT"),
        ("LINEABOVE", (0, 2), (-1, 2), 1, colors.HexColor("#111827")),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))

    story.append(totals_table)
    story.append(Spacer(1, 24))
    story.append(Paragraph(
        "Generated by GST Management System.",
        styles["BodyText"]
    ))

    doc.build(story)
    return file_path
